anime_dictionarie = {
    "Denji": "./Game/Bilder/denji.jpg",
    "Megumin": "./Game/Bilder/megumin.jpg",
    "Emma": "./Game/Bilder/nacken_tatto.png",
    "Gojo": "./Game/Bilder/Gojo.jpg",
    "Roxy": "./Game/Bilder/roxy.jpg",
    "Sanemi": "./Game/Bilder/Sanemi.jpg",
    "Nina": "./Game/Bilder/Nina.jpg",
    "Reina": "./Game/Bilder/Reina.jpg",
    "Yui": "./Game/Bilder/Yui.jpg",
    "Catherine ": "./Game/Bilder/Catherine.jpg",
    "Edward": "./Game/Bilder/Edward.jpg",
    "Tadaomi": "./Game/Bilder/Tadaomi.jpg",
    "Kaede": "./Game/Bilder/Kaede.jpg",
    "Hange": "./Game/Bilder/Hange.jpg",
    "Annie": "./Game/Bilder/Annie.jpg",
    "Gouhin": "./Game/Bilder/Gouhin.jpg",
    "Haru": "./Game/Bilder/Haru.jpg",
    "Guts": "./Game/Bilder/Guts.jpg",
    "Griffith": "./Game/Bilder/Griffith.jpg",
    "Mephisto": "./Game/Bilder/Mephisto.jpg",
    "Shirou": "./Game/Bilder/Shirou.jpg",
    "Rebecca": "./Game/Bilder/Rebecca.jpg",
    "Maine": "./Game/Bilder/Maine.jpg",
    "Giyuu": "./Game/Bilder/Giyuu.jpg",
    "Kayo": "./Game/Bilder/Kayo.jpg",
    "Hiromi": "./Game/Bilder/Hiromi.jpg",
    "Rikka": "./Game/Bilder/Rikka.jpg",
    "Yuuta": "./Game/Bilder/Yuuta.jpg",
    "Thorkell": "./Game/Bilder/Thorkell.jpg",
    "Thors": "./Game/Bilder/Thors.jpg",
    "Matsuboshi": "./Game/Bilder/Matsuboshi.jpg",
    "Yuu": "./Game/Bilder/Yuu.jpg",
    "Matsuboshi": "./Game/Bilder/Matsuboshi.jpg",
    "Chika": "./Game/Bilder/Chika.jpg",

}
