anime_list_easy = {
    "Denji": "./Bilder/denji.jpg",
    "Megumin": "./Bilder/megumin.jpg",
    "Emma": "./Bilder/nacken_tatto.png",
    "Gojo": "./Bilder/Gojo.jpg",
    "Roxy": "./Bilder/roxy.jpg",
    "Sanemi": "./Bilder/Sanemi.jpg",
    "Nina": "./Bilder/Nina.jpg",
    "Reina": "./Bilder/Reina.jpg",
    "Yui": "./Bilder/Yui.jpg",
    "Catherine ": "./Bilder/Catherine.jpg",
    "Edward": "./Bilder/Edward.jpg",
    "Tadaomi": "./Bilder/Tadaomi.jpg",
    "Kaede": "./Bilder/Kaede.jpg",
    "Hange": "./Bilder/Hange.jpg",
    "Annie": "./Bilder/Annie.jpg",
    "Gouhin": "./Bilder/Gouhin.jpg",
    "Haru": "./Bilder/Haru.jpg",
    "Guts": "./Bilder/Guts.jpg",
    "Griffith": "./Bilder/Griffith.jpg",
    "Mephisto": "./Bilder/Mephisto.jpg",
    "Shirou": "./Bilder/Shirou.jpg",
    "Rebecca": "./Bilder/Rebecca.jpg",
    "Maine": "./Bilder/Maine.jpg",
    "Giyuu": "./Bilder/Giyuu.jpg",
    "Kayo": "./Bilder/Kayo.jpg",
    "Hiromi": "./Bilder/Hiromi.jpg",
    "Rikka": "./Bilder/Rikka.jpg",
    "Yuuta": "./Bilder/Yuuta.jpg",
    "Thorkell": "./Bilder/Thorkell.jpg",
    "Thors": "./Bilder/Thors.jpg",
    "Matsuboshi": "./Bilder/Matsuboshi.jpg",
    "Yuu": "./Bilder/Yuu.jpg",
    "Matsuboshi": "./Bilder/Matsuboshi.jpg",
    "Chika": "./Bilder/Chika.jpg",

}
anime_list_medium = {

}
